apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tfc-agent
  namespace: tfc-agent
spec:
  interval: 5m
  chart:
    spec:
      chart: tfc-agent
      version: "0.5.0"
      sourceRef:
        kind: HelmRepository
        name: innovationnorway
  values:
    serviceAccount:
      create: true
    terraformCloudSecrets:
      enabled: false
    command:
      enabled: true
      cmd:
        - /bin/bash
        - -c
      args:
        - "cat /vault/secrets/config"
        - "source /vault/secrets/config"
        - "while true; echo tick; sleep 2; done"
    env:
    - name: VAULT_ADDR
      value: https://vault.innovasjonnorge.no
    podAnnotations:
      vault.hashicorp.com/agent-inject: 'true'
      vault.hashicorp.com/role: 'tfc-agent'
      vault.hashicorp.com/agent-inject-secret-config: 'tfc-config/data/agent'
      # Environment variable export template
      vault.hashicorp.com/agent-inject-template-config: |
        {{- with secret "tfc-config/data/agent" -}}
          export AGENT_NAME="{{ .Data.data.name }}"
          export AGENT_TOKEN="{{ .Data.data.token }}"
        {{- end }}