apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tfc-agent.fullname" . }}
  labels:
    {{- include "tfc-agent.labels" . | nindent 4 }}
data:
  TFC_AGENT_NAME: {{ .Values.terraformCloudSecrets.agentName | b64enc }}
  TFC_AGENT_TOKEN: {{ .Values.terraformCloudSecrets.agentToken | b64enc }}

