apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: activemq
    workload: ipunkt
  name: activemq
  namespace: ipunkt
spec:
  selector:
    matchLabels:
      app: activemq
      workload: ipunkt
  serviceName: activemq
  replicas: 1
  template:
    metadata:
      labels:
        app: activemq
        workload: ipunkt
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
      containers:
      - name: activemq
        image: rmohr/activemq:5.15.9
        securityContext:
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        ports:
        - containerPort: 61616
          name: activemq
        volumeMounts:
        - name: amq-data
          mountPath: /opt/activemq/data
  volumeClaimTemplates:
  - metadata:
      name: amq-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  namespace: ipunkt
  labels:
    app: activemq
    workload: ipunkt
  name: activemq
spec:
  ports:
  - name: 61616-61616
    port: 61616
    protocol: TCP
    targetPort: 61616
  selector:
    app: activemq
    workload: ipunkt