apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: ipunkt
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "10.2.6"
      sourceRef:
        kind: HelmRepository
        name: bitnami
securityContext:
  runAsUser: 2000
containerSecurityContext:
  runAsUser: 2000
  allowPrivilegeEscalation: false