apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: ipunkt
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      version: "13.3.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami