apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-ha
  namespace: vault-ha
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.9.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
  values:
    server:
      extraVolumes:
        - type: secret
          name: seal-secret-config
      extraArgs: "-config /vault/userconfig/seal-secret-config/config.hcl"
      ha:
        enabled: true
        replicas: 3
        raft:
          enabled: true
      ingress:
        enabled: true
        hosts:
          - host: vault.innovasjonnorge.no
            paths:
              - backend:
                  serviceName: vault-ha
                  servicePort: 8200
                path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: chart-example-tls
            hosts:
              - vault.innovasjonnorge.no
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 384Mi
          cpu: 300m
