{{- $container_port := .Values.service.internalPort -}}
{{- $service_port := .Values.service.externalPort -}}
{{- $admin_port := default 8877 .Values.service.gatewayAdminPort -}}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: gateway
{{ include "helm.labels" . | indent 4 }}
  name: gateway
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind:  AuthService
      name:  authentication
      auth_service: "auth-svc:8000"
      path_prefix: "/v0/authz"
      allowed_request_headers:
      - "x-forwarded-access-token"
      ---
{{- if (eq "endpoint" .Values.apigateway.serviceResolver) }}
      apiVersion: getambassador.io/v1
      kind: KubernetesEndpointResolver
      name: endpoint
      ---
{{- end }}
      apiVersion: ambassador/v1
      kind:  Module
      name:  ambassador
      config:
        service_port: {{ $container_port }}
{{- if (eq "endpoint" .Values.apigateway.serviceResolver) }}
        resolver: endpoint
        load_balancer:
          policy: round_robin
{{- end }}
{{- if and .Values.secrets.apiTlsCrt .Values.secrets.apiTlsKey }}
      ---
      apiVersion: ambassador/v1
      kind:  Module
      name:  tls
      config:
        server:
          enabled: True
          secret: ambassador-certs
{{- end }}
spec:
  ports:
  - name: http
    port: {{ $service_port }}
    targetPort: {{ $container_port }}
  selector:
    service: gateway
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ $.Release.Namespace }}
  name: gateway-admin
  labels:
    service: gateway
{{ include "helm.labels" . | indent 4 }}
spec:
  ports:
  - name: metrics
    port: {{ $admin_port }}
    targetPort: {{ $admin_port }}
  selector:
    service: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "helm.labels" . | indent 4 }}
    component: gateway
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      service: gateway
  template:
    metadata:
      labels:
        service: gateway
        component: gateway
{{ include "helm.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ template "serviceAccountName" . }}
{{- if or .Values.secrets.dockerConfig .Values.secrets.dockerConfigPath }}
      imagePullSecrets:
        - name: k10-ecr
{{- end }}
      securityContext:
{{ toYaml .Values.services.securityContext | indent 8 }}
      containers:
      - name: ambassador
        image: {{ include "k10.ambImage" . }}
        resources:
          limits:
            cpu: 1
            memory: 400Mi
          requests:
            cpu: 200m
            memory: 100Mi
        env:
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AMBASSADOR_SINGLE_NAMESPACE
          value: "true"
        livenessProbe:
          httpGet:
            path: /ambassador/v0/check_alive
            port: {{ $admin_port }}
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ambassador/v0/check_ready
            port: {{ $admin_port }}
          initialDelaySeconds: 30
          periodSeconds: 3
      restartPolicy: Always
