# Vault Helm values
# helm install 
server:
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 384Mi
      cpu: 300m
  standalone:
    enabled: "-"
    # config: |
    #   storage "file" {
    #     path = "/vault/data"
    #   }
    #   listener "tcp" {
    #     address     = "0.0.0.0:8200"
    #     tls_disable = 0
    #   }
    #   seal "azurekeyvault" {
    #     tenant_id      = "c39d49f7-9eed-4307-b032-bb28f3cf9d79"
    #     vault_name     = "hub-prod-shared-kv"
    #     key_name       = "platform-vault"
    #   }
  # extraEnvironmentVars:
  #   VAULT_SEAL_TYPE: azurekeyvault
  #   VAULT_AZUREKEYVAULT_VAULT_NAME: "hub-prod-shared-kv"
  #   VAULT_AZUREKEYVAULT_KEY_NAME: "platform-vault"
  #   AZURE_TENANT_ID: "c39d49f7-9eed-4307-b032-bb28f3cf9d79"
  #   AZURE_CLIENT_ID: "c3a222f2-9769-46ac-a813-f68454bf1414"

# HA not supported by Azure storage, need to do extra research
  # ha:
  #   enabled: true
  # config: |
  #   seal "azurekeyvault" {
  #     client_id      = "f1a55063-464f-4dc3-8375-7e9156d5c9b8"
  #     tenant_id      = "c39d49f7-9eed-4307-b032-bb28f3cf9d79"
  #     vault_name     = "hub-prod-shared-kv"
  #     key_name       = "platform-vault"
  #   }
  #   replicas: 3