---
apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: test
spec:
  url: https://charts.bitnami.com/bitnami
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: test
spec:
  interval: 5m
  chart:
    spec:
      chart: nginx
      version: "4.1.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
---
