---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-vault
spec:
  rules:
  - host: grafana.innovationnorway.io
    http:
      paths:
      - path: /
        backend:
          serviceName: prom-grafana
          servicePort: 80
  tls:
  - hosts:
    - grafana.innovationnorway.io
    secretName: grafana-innovationnorway-io