apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp-exporter
  namespace: monitoring
  labels:
    app: snmp-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snmp-exporter
  template:
    metadata:
      labels:
        app: snmp-exporter
    spec:
      containers:
      - name: snmp-exporter
        image: prom/snmp-exporter:v0.20.0
        ports:
        - containerPort: 9116
        volumeMounts:
        - name: config
          mountPath: /etc/snmp-exporter/snmp.yml
          subPath: config.yml
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: config
        configMap:
          name: snmp-exporter
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: snmp-exporter
  namespace: monitoring
data:
  config.yaml: |
    scrape_configs:
    - job_name: 'snmp'
      static_configs:
        - targets:
          - 172.20.20.101
          - 172.20.20.102
          - 172.20.20.103
          - 172.20.20.104
          - 172.20.20.105
          - 172.20.20.106
          - 172.20.20.107
          - 172.20.20.108
          - 172.20.20.109
          - 172.20.20.240
      metrics_path: /snmp
      params:
        module: [if_mib]
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: 127.0.0.1:9116  # The SNMP exporter's real hostname:port.