apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 5m
  chart:
    spec:
      chart: netbox
      version: "1.2.9"
      sourceRef:
        kind: HelmRepository
        name: enix
  values:
    existingEnvSecret: netbox