---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mic
  namespace: podidentity
spec:
  podSelector:
    matchLabels:
        app.kubernetes.io/name: aad-pod-identity
        app.kubernetes.io/component: mic
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - {}
  egress:
    - {}